from array import *
import itertools

recipeAingredients = [] 

# A
recipeAingredients.append(["butter", "egg", "milk", "parmesan", "cheddar", "american cheese", "sour cream", "cream cheese", "mozarella", "yogurt", "cream", "evaporated milk", "whipped cream", "half and half", "feta", "monterey jack cheese", "condensed milk", "cottage cheese", "ice cream", "swiss cheese", "velveeta", "frosting", "buttermilk", "ricotta", "goat cheese", "provolone", "blue cheese", "powdered milk", "colby cheese", "pepper jack", "italian cheese", "soft cheese", "gouda", "peperjack cheese", "romano", "brie", "pizza cheese", "ghee", "creme fraiche", "cheese soup", "gruyere", "pecorino cheese", "custard", "muenster", "queso fresco cheese", "hard cheese", "havarti cheese", "asiago", "mascarpone", "neufchatel", "halloumi", "paneer", "bick cheese", "camembert cheese", "goat milk", "garlic herb cheese", "edam cheese", "machego", "fontina", "stilton cheese", "emmenthaler cheese", "red leicester cheese", "jarlsberg cheese", "bocconici cheese", "farmer cheese", "creme de cassis", "wendesleydale cheese", "longhorn cheese", "double gloucester cheese", "raclette cheese", "lancashire cheese", "ceshire"]);
recipeAingredients.append(["lemon apple", "banana lime", "strawberry orange", "pineapple blueberry", "raisin", "coconut grape", "peach raspberry", "cranberry", "mango", "pear", "blackberry", "cherry", "watermelon", "berries", "kiwi grapefruit", "mandarin", "craisins", "cantaloupe", "plum", "apricot", "clementine", "prunes", "apple", "butter", "pomegranate", "nectarine fig", "tangerine papaya", "rhubarb", "sultanas", "plantain", "currant", "passion fruit", "guava", "persimmons", "lychee", "lingonberry", "tangelos", "kumquat", "boysenberry", "star fruit", "quince", "honeydew", "crabapples"]);
recipeAingredients.append(["rice", "pasta", "flour", "bread", "baking powder", "baking soda", "bread", "crumbs", "cornstarch", "rolled oats", "noodle flour", "tortillas", "pancake", "mix yeast", "cracker", "quinoa", "brown rice", "cornmeal", "self rising", "flour", "cake mix", "saltines", "popcorn", "macaroni", "cheese", "mix corn", "tortillas", "ramen cereal", "biscuits", "stuffing", "couscous", "pie", "crust", "bisquick", "chips", "angel hair", "coconut", "flake bread", "flour", "croutons", "lasagne", "pizza dough", "bagel puff", "pastry", "hot dog bun", "barley", "multigrain bread", "potato flakes", "pretzel cornbread", "english muffin", "cornflour crescent", "roll dough", "cream of wheat", "coconut flour", "risotto muffin", "bicarbonate of soda", "ravioli", "wheat rice", "flour", "polenta baguette", "gnocchi", "vermicelli", "semolina", "wheat germ", "buckwheat croissants", "yeast", "flake", "pierogi", "matzo", "meal", "rye tapioca", "flour shortcrust", "pastry potato", "starch breadsticks", "ciabatta spelt", "angel food", "tapioca starch", "starch whole", "wheat flour", "gram flour", "sourdough starter", "wafer bran", "challah sponge", "cake", "malt extract", "sorghum flour"]);
recipeAingredients.append(["sugar", "brown sugar", "honey", "confectioners sugar", "maple syrup", "corn syrup", "molasses", "artificial sweetener", "agave nectar"]);
recipeAingredients.append(["bouillon", "ground ginger", "sesame seed", "cream of tartar", "chili sauce", "soya sauce", "apple cider", "hoisin sauce", "liquid smoke", "rice", "wine", "vegetable bouillon", "poppy seed", "balsamic glaze", "miso wasabi", "fish stock", "rose water", "pickling salt", "champagne", "vinegar", "bbq rub", "jamaican jerk", "spice accent", "seasoning pickling", "spice mustard", "powder mango", "powder adobo", "seasoning kasuri", "methi caribbean", "jerk seasoning", "brine matcha", "powder cassia"]);
recipeAingredients.append(["tomato sauce", "tomato paste", "salsa", "pesto", "alfredo sauce", "beef gravy", "curry paste", "chicken gravy", "cranberry sauce", "turkey gravy", "mushroom gravy", "sausage gravy", "onion gravy", "cream gravy", "pork gravy", "tomato gravy", "giblet grayvy"]);
recipeAingredients.append(["margarine", "coconut milk", "almond milk", "soy milk", "rice milk", "hemp milk", "non dairy creamer"]);

recipeBingredients = [] 

# B
recipeBingredients.append(["chicken breast", "ground beef", "bacon sausage", "beef", "steak", "ham", "hot dog", "pork", "chops", "chicken thighs", "ground turkey", "cooked chicken", "turkey", "pork", "pepperoni", "whole chicken", "chicken leg", "ground pork", "chorizo", "chicken wings", "beef", "roast", "polish sausage", "salami pork", "roast ground", "chicken pork", "ribs", "spam", "venison pork", "shoulder bologna", "bratwurst prosciutto", "lamb corned", "beef chicken", "roast lamb", "chops pancetta", "ground lamb", "beef", "ribs", "duck", "pork", "belly", "beef liver", "leg of lamb", "canadian bacon", "beef shank", "veal chicken", "giblets cornish", "hen lamb", "shoulder", "lamb shank", "deer ground", "veal pastrami", "rabbit sliced", "turkey pork", "loin elk", "beef suet", "veal cutlet", "lamb loin", "marrow bones", "goose chicken", "tenders veal", "chops quail", "oxtail pheasant", "lamb", "liver", "moose", "turkey", "liver pork", "liver veal", "shank foie", "gras", "beef sirloin", "liver sausage", "sweetbread", "wild boar", "snail pigeon", "duck liver", "goose liver", "grouse ostrich", "soppressata alligator"]);
recipeBingredients.append(["mayonnaise", "ketchup", "mustard", "vinegar", "soy", "sauce", "balsamic", "vinegar", "worcestershire", "hot sauce", "barbecue sauce", "ranch dressing", "wine vinegar", "apple cider", "vinegar cider", "vinegar", "italian dressing", "rice vinegar", "salad", "dressing tabasco", "fish sauce", "teriyaki steak", "sauce tahini", "enchilada sauce", "vinaigrette dressing", "oyster sauce", "honey", "mustard", "sriracha", "caesar dressing", "taco sauce", "mirin blue", "cheese dressing", "sweet and sour", "sauce thousand", "island picante", "sauce", "buffalo sauce", "french dressing", "tartar sauce", "cocktail sauce", "marsala adobo", "sauce tzatziki", "sauce sesame", "dressing ponzu", "duck sauce", "pickapeppa sauce", "yuzu juice", "cream sauce"]);
recipeBingredients.append(["olive oil", "vegetable oil", "cooking spray", "canola oil", "shortening", "sesame oil", "coconut oil", "peanut oil", "sunflower oil", "lard", "grappe seed oil", "corn oil", "almand oil", "avocado oil", "safflower oil", "Walnut oil", "hazeinut oil", "palm oil", "saybean oil", "mustard oil", "pistachio oil", "soya oil"]);
recipeBingredients.append(["bouillon", "ground ginger", "sesame seed", "cream of tartar", "chili sauce", "soya sauce", "apple cider", "hoisin sauce", "liquid smoke", "rice", "wine", "vegetable bouillon", "poppy seed", "balsamic glaze", "miso wasabi", "fish stock", "rose water", "pickling salt", "champagne", "vinegar", "bbq rub", "jamaican jerk", "spice accent", "seasoning pickling", "spice mustard", "powder mango", "powder adobo", "seasoning kasuri", "methi caribbean", "jerk seasoning", "brine matcha", "powder cassia"]);
recipeBingredients.append(["tomato sauce", "tomato paste", "salsa", "pesto", "alfredo sauce", "beef gravy", "curry paste", "chicken gravy", "cranberry sauce", "turkey gravy", "mushroom gravy", "sausage gravy", "onion gravy", "cream gravy", "pork gravy", "tomato gravy", "giblet grayvy"]);
recipeBingredients.append(["green beans", "peas", "black beans", "chickpea", "lentil", "refried beans", "hummus chili", "beans lima", "beans", "kidney beans", "pinto beans", "edamame split", "peas snap", "peas soybeans", "cannellini beans", "navy beans", "french beans", "red beans", "great northern", "beans", "fava beans"]);
recipeBingredients.append(["white wine", "beer", "red wine", "vodka", "rum", "whiskey", "tequila", "sherry", "bourbon", "cooking", "wine whisky", "liqueur brandy", "gin kahlua", "irish cream", "triple sec", "champagne", "amaretto", "cabernet", "sauvignon", "vermouth", "bitters", "maraschino", "sake grand", "marnier masala", "dessert wine", "schnapps port", "wine sparkling", "wine cognac", "chocolate liqueur", "burgundy wine", "limoncello creme", "menthe bloody", "mary raspberry", "liquor curacao", "frangelico shaoxing", "wine absinthe", "madeira wine", "ouzo anisette", "grappa ciclon", "drambuie"]);
recipeBingredients.append(["peanut butter", "almond", "walnut", "pecan", "peanut", "cashew", "flax", "pine nut", "pistachio", "almond meal", "hazelnut", "macadamia", "almond paste", "chestnut", "praline", "macaroon"]);
recipeBingredients.append(["margarine", "coconut milk", "almond milk", "soy milk", "rice milk", "hemp milk", "non dairy creamer"]);
recipeBingredients.append(["chocolate", "apple sauce", "strawberry jam", "graham cracker", "marhsmallow", "chocolate syrup", "potato chips", "nutella", "chocolate morsels", "bittersweet chocolate", "pudding mix", "rasperry jam", "dark chocolate", "chocolate chips", "jam", "white chocolate", "brownie mix", "chocolate pudding", "jello", "caramel", "chocolate powder", "candy", "corn chips", "cookies", "apricot jam", "chocolate bar", "cookie dough", "oreo", "doritos", "chocolate cookies", "butterscoth", "blackberry preserves", "blueberry jam", "peach preserves", "cherry jam", "fig jam", "plum jam", "cinnamon roll", "fudge", "cookie crumb", "grape jelly", "chilli jam", "lady fingers", "black pudding", "chocolate wafer", "gummy worms", "biscott biscuit", "doughnut", "amaretti cookies", "apple jelly", "red pepper jelly", "orange jelly", "jalapeno jelly", "mint jelly", "currant jelly", "lemon jelly", "quince jelly"]);
recipeBingredients.append(["coffee", "orange juice", "tea", "green tea", "apple juice", "tomato juice", "coke", "chocolate milk", "pinneaple juice", "lemonade", "cranberry juice", "expresso", "fruit juice", "ginger ale", "club soda", "sprite", "kool aid", "grenadine", "margarita mix", "cherry juice", "pepsi", "mountain dew"]);

ingredient = [ingredient for cathegory in recipeAingredients for ingredient in cathegory]
for cathegory in itertools.permutations(ingredient, 7):
	print(" ".join(cathegory))

ingredient = [ingredient for cathegory in recipeBingredients for ingredient in cathegory]
for cathegory in itertools.permutations(ingredient, 11):
	print(" ".join(cathegory))
