let fs = require('fs');

let textblock;

function hashingProceduralScriptGeneration() {

    for (let i1 = 0; i1 < 2000; i1++) {

        let myToneJSscriptname = ["tonejs" + i1 + ".html"];

        console.log(myToneJSscriptname, "utf-8");

        textblock = "\n\t\t <!DOCTYPE html>"
            + "\n\t\t <html lang='en' >"
            + "\n\t\t <head>"
            + "\n\t\t   <meta charset='UTF-8'>"
            + "\n\t\t   <title>CodePen - Tone JS Tutorial Part 3</title>"
            + "\n\t\t   <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css'>"
            + "\n\t\t <link rel='stylesheet' href='style.css'>"
            + "\n\t\t </head>"
            + "\n\t\t <body>"
            + "\n\t\t <style>"
            + "\n\t\t   html, body {"
            + "\n\t\t   height: 100%;"
            + "\n\t\t }"
            + "\n\t\t header {"
            + "\n\t\t   overflow: hidden;"
            + "\n\t\t   height: 100%;"
            + "\n\t\t }"
            + "\n\t\t header input {"
            + "\n\t\t   position: absolute;"
            + "\n\t\t   left: -9999px;"
            + "\n\t\t }"
            + "\n\t\t header input#chord-1:checked ~ ul label[for='chord-1'] {"
            + "\n\t\t   background: #ff0000;"
            + "\n\t\t }"
            + "\n\t\t header input#chord-2:checked ~ ul label[for='chord-2'] {"
            + "\n\t\t   background: #ff0000;"
            + "\n\t\t }"
            + "\n\t\t header input#chord-3:checked ~ ul label[for='chord-3'] {"
            + "\n\t\t   background: #ff0000;"
            + "\n\t\t }"
            + "\n\t\t header input#chord-4:checked ~ ul label[for='chord-4'] {"
            + "\n\t\t   background: #ff0000;"
            + "\n\t\t }"
            + "\n\t\t header input#chord-5:checked ~ ul label[for='chord-5'] {"
            + "\n\t\t   background: #ff0000;"
            + "\n\t\t }"
            + "\n\t\t header ul {"
            + "\n\t\t   height: 100%;"
            + "\n\t\t   list-style: none;"
            + "\n\t\t   margin: 0;"
            + "\n\t\t   padding: 0;"
            + "\n\t\t   display: -webkit-box;"
            + "\n\t\t   display: flex;"
            + "\n\t\t }"
            + "\n\t\t header ul li {"
            + "\n\t\t   -webkit-box-flex: 1;"
            + "\n\t\t           flex: 1;"
            + "\n\t\t }"
            + "\n\t\t header ul li label {"
            + "\n\t\t   height: 100%;"
            + "\n\t\t   display: block;"
            + "\n\t\t   cursor: pointer;"
            + "\n\t\t   text-align: center;"
            + "\n\t\t   padding: 0.5rem;"
            + "\n\t\t   background: black;"
            + "\n\t\t   color: white;"
            + "\n\t\t   display: -webkit-box;"
            + "\n\t\t   display: flex;"
            + "\n\t\t   -webkit-box-orient: vertical;"
            + "\n\t\t   -webkit-box-direction: normal;"
            + "\n\t\t           flex-direction: column;"
            + "\n\t\t   -webkit-box-pack: center;"
            + "\n\t\t           justify-content: center;"
            + "\n\t\t   align-content: center;"
            + "\n\t\t   font-size: 3rem;"
            + "\n\t\t }"
            + "\n\t\t header ul li + li {"
            + "\n\t\t   border-left: 4px solid #191919;"
            + "\n\t\t }"
            + "\n\t\t </style>"
            + "\n\t\t <!-- partial:index.partial.html -->"
            + "\n\t\t <header>"
            + "\n\t\t   <input id='chord-1' value='1' type='radio' name='chord' />"
            + "\n\t\t   <input id='chord-2' value='2' type='radio' name='chord' />"
            + "\n\t\t   <input id='chord-3' value='3' type='radio' name='chord' />"
            + "\n\t\t   <input id='chord-4' value='4' type='radio' name='chord' />"
            + "\n\t\t   <input id='chord-5' value='5' type='radio' name='chord' />"
            + "\n\t\t   <ul>"
            + "\n\t\t     <li><label for='chord-1'>1</label></li>"
            + "\n\t\t     <li><label for='chord-2'>2</label></li>"
            + "\n\t\t     <li><label for='chord-3'>3</label></li>"
            + "\n\t\t     <li><label for='chord-4'>4</label></li>"
            + "\n\t\t     <li><label for='chord-5'>5</label></li>"
            + "\n\t\t   </ul>"
            + "\n\t\t   <!-- replace this by some sort of patterns sequence within the browser-->"
            + "\n\t\t </header>"
            + "\n\t\t <script>"
            + "\n\t\t   console.clear();"
            + "\n\t\t // UPDATE: there is a problem in chrome with starting audio context"
            + "\n\t\t //  before a user gesture. This fixes it."
            + "\n\t\t var started = false;"
            + "\n\t\t document.documentElement.addEventListener('mousedown', () => {"
            + "\n\t\t   if (started) return;"
            + "\n\t\t   started = true;"
            + "\n\t\t   const $inputs = document.querySelectorAll('input'),"
            + "\n\t\t   chords = ["
            + "\n\t\t   'A0 C0 E0 G0 A0 C0', 'F0 A0 C0 E0 A0 G0', 'D0 E0 F0 G0 B0 D0 F0 B0 G0',"
            + "\n\t\t   'D0 F0 A0 C0 D0 G0', 'E0 G0 B0 D0 C0 F0']."
            + "\n\t\t   map(formatChords);"
            + "\n\t\t   console.log(chords);"
            + "\n\t\t   var chordIdx = 0,"
            + "\n\t\t   step = 0;"
            + "\n\t\t   const synth = new Tone.Synth();"
            + "\n\t\t   const gain = new Tone.Gain(0.7);"
            + "\n\t\t   synth.oscillator.type = 'sine';"
            + "\n\t\t   gain.toMaster();"
            + "\n\t\t   synth.connect(gain);"
            + "\n\t\t   Array.from($inputs).forEach($input => {"
            + "\n\t\t     $input.addEventListener('change', () => {"
            + "\n\t\t       if ($input.checked) handleChord($input.value);"
            + "\n\t\t     });"
            + "\n\t\t   });"
            + "\n\t\t   function handleChord(valueString) {"
            + "\n\t\t     chordIdx = parseInt(valueString) - 1;"
            + "\n\t\t   }"
            + "\n\t\t   Tone.Transport.scheduleRepeat(onRepeat, '16n');"
            + "\n\t\t   Tone.Transport.start();"
            + "\n\t\t   Tone.Transport.bpm.value = 90;"
            + "\n\t\t   function onRepeat(time) {"
            + "\n\t\t     let chord = chords[chordIdx],"
            + "\n\t\t     note = chord[step % chord.length];"
            + "\n\t\t     synth.triggerAttackRelease(note, '16n', time);"
            + "\n\t\t     step++;"
            + "\n\t\t   }"
            + "\n\t\t   // DOWN THE LINE THIS WILL MAKE THINGS EASIER"
            + "\n\t\t   function formatChords(chordString) {"
            + "\n\t\t     let chord = chordString.split(' ');"
            + "\n\t\t     let arr = [];"
            + "\n\t\t     for (let i = 0; i < 2; i++) {"
            + "\n\t\t       for (let j = 0; j < chord.length; j++) {"
            + "\n\t\t         let noteOct = chord[j].split(''),"
            + "\n\t\t         note = noteOct[0];"
            + "\n\t\t         let oct = noteOct[1] === '0' ? i + 4 : i + 5;"
            + "\n\t\t         note += oct;"
            + "\n\t\t         arr.push(note);"
            + "\n\t\t       }"
            + "\n\t\t     }"
            + "\n\t\t     return arr;"
            + "\n\t\t   }"
            + "\n\t\t });"
            + "\n\t\t </script>"
            + "\n\t\t <!-- partial -->"
            + "\n\t\t   <script src='https://cdnjs.cloudflare.com/ajax/libs/tone/0.12.63/Tone.js'></script><script  src='./script.js'></script>"
            + "\n\t\t </body>"
            + "\n\t\t </html>";


        fs.writeFileSync("./tonejs1/" + myToneJSscriptname, textblock);

    }

    return 0;

}

hashingProceduralScriptGeneration();